# Generated by Django 4.2.2 on 2023-07-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medapp", "0002_products_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
