# Generated by Django 4.2.2 on 2023-07-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medapp", "0003_alter_customer_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingaddress",
            name="street",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
